// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsDocker")>]
[<assembly: AssemblyProductAttribute("FsDocker")>]
[<assembly: AssemblyDescriptionAttribute("F# Client for Docker Remote API based on Docker.DotNet Project")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsDocker"
    let [<Literal>] AssemblyProduct = "FsDocker"
    let [<Literal>] AssemblyDescription = "F# Client for Docker Remote API based on Docker.DotNet Project"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
